In [1]:
# Perform following operations/functions based on arrays
# a. Create a NumPy array of integers from 1 to 10.
# b. Create a NumPy array of zeros of size 5.
# c. Create a NumPy array of ones of shape (3, 3).
# d. Find the sum and mean of a NumPy array.
# e. Access the 3rd element from a NumPy array.
import numpy as np
# a. Create a NumPy array of integers from 1 to 10
arr = np.arange(1, 11)
print("Array from 1 to 10:", arr)
# b. Create a NumPy array of zeros of size 5
zeros_arr = np.zeros(5)
print("Zeros array of size 5:", zeros_arr)
# c. Create a NumPy array of ones of shape (3, 3)
ones_arr = np.ones((3, 3))
print("Ones array of shape (3,3):")
print(ones_arr)
# d. Find the sum and mean of a NumPy array
sample_arr = np.array([10, 20, 30, 40, 50])
print("Sample array:", sample_arr)
print("Sum of array:", np.sum(sample_arr))
print("Mean of array:", np.mean(sample_arr))
# e. Access the 3rd element from a NumPy array
third_element = sample_arr[2] # index starts from 0
print("3rd element of the array:", third_element)

Array from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]
Zeros array of size 5: [0. 0. 0. 0. 0.]
Ones array of shape (3,3):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Sample array: [10 20 30 40 50]
Sum of array: 150
Mean of array: 30.0
3rd element of the array: 30
