In [1]:
# Perform following operations/functions based on arrays
# a. Create a 2D array (3×4) and find its shape and dimension.
# b. Find the maximum and minimum value from a NumPy array.
# c. Perform element-wise addition and multiplication of two arrays.
# d. Reshape a 1D array of size 12 into a 3×4 matrix.
# e. Find all even numbers from a NumPy array using boolean indexing.
import numpy as np
# a. Create a 2D array (3×4) and find its shape and dimension
arr_2d = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]
])
print("2D Array:")
print(arr_2d)
print("Shape of array:", arr_2d.shape)
print("Dimension of array:", arr_2d.ndim)
print()
# b. Find the maximum and minimum value from a NumPy array
print("Maximum value:", np.max(arr_2d))
print("Minimum value:", np.min(arr_2d))
print()
# c. Element-wise addition and multiplication of two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise Addition:", arr1 + arr2)
print("Element-wise Multiplication:", arr1 * arr2)
print()
# d. Reshape a 1D array of size 12 into a 3×4 matrix
arr_1d = np.arange(1, 13)
reshaped_arr = arr_1d.reshape(3, 4)
print("1D Array:", arr_1d)
print("Reshaped 3×4 Array:")
print(reshaped_arr)
print()
# e. Find all even numbers using boolean indexing
even_numbers = arr_1d[arr_1d % 2 == 0]
print("Even numbers from array:", even_numbers)


2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array: (3, 4)
Dimension of array: 2

Maximum value: 12
Minimum value: 1

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Element-wise Addition: [ 6  8 10 12]
Element-wise Multiplication: [ 5 12 21 32]

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3×4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Even numbers from array: [ 2  4  6  8 10 12]
