In [1]:
# Perform following operations based on NumPy – Random Module
# a. Generate 10 random integers between 1 and 100
# b. Create a 3×3 array of random numbers
# c. Set a random seed and generate random numbers
# d. Find the mean of randomly generated numbers
import numpy as np
# a. Generate 10 random integers between 1 and 100
random_integers = np.random.randint(1, 101, size=10)
print("10 Random integers between 1 and 100:", random_integers)
# b. Create a 3×3 array of random numbers (float values between 0 and 1)
random_3x3 = np.random.rand(3, 3)
print("\n3×3 Array of random numbers:")
print(random_3x3)
# c. Set a random seed and generate random numbers
np.random.seed(42) # set seed output are same for all time
seeded_random_numbers = np.random.rand(5)
print("\nRandom numbers after setting seed:", seeded_random_numbers)
# d. Find the mean of randomly generated numbers
mean_value = np.mean(seeded_random_numbers)
print("\nMean of randomly generated numbers:", mean_value)


10 Random integers between 1 and 100: [85 71 69 98 30 41 98 77 50 87]

3×3 Array of random numbers:
[[0.08928259 0.96383885 0.15853822]
 [0.30148425 0.00594735 0.15906297]
 [0.9859854  0.91274904 0.19350291]]

Random numbers after setting seed: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Mean of randomly generated numbers: 0.5623850983416314
